<?xml version="1.0" encoding="UTF-8"?>
<!--Principal Maven Project Balise: -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <!-- maven model version -->
    <modelVersion>4.0.0</modelVersion>

    <!--Project coordinates: groupId, artifactId, version, name -->
    <groupId>com.parabank</groupId>

    <artifactId>parabank-kata</artifactId>

    <version>1.0-SNAPSHOT</version>

    <name>ParaBank Test Automation Kata Exercise</name>

    <properties>
        <!-- Java compiler settings for maven-->
        <maven.compiler.release>17</maven.compiler.release>
        <!-- for source and reporting encoding files-->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <!-- adding version properties for TestNG, Cucumber, and Maven Surefire -->
        <cucumber.version>7.20.1</cucumber.version>
        <testng.version>7.10.2</testng.version>
        <maven.surefire.version>3.5.2</maven.surefire.version>

        <!--adding RestAssured version Properties 5.5.0-->
        <rest.assured.version>5.5.0</rest.assured.version>
    </properties>

    <!--Dependencies: Cucumber, TestNG-->
    <dependencies>

    <dependency>
        <!--cucumber for java-->
        <groupId>io.cucumber</groupId>
        <artifactId>cucumber-java</artifactId>
        <version>${cucumber.version}</version>
        <scope>test</scope>
    </dependency>

    <dependency>
        <!--cucumber for testNG-->
        <groupId>io.cucumber</groupId>
        <artifactId>cucumber-testng</artifactId>
        <version>${cucumber.version}</version>
        <scope>test</scope>
    </dependency>

    <dependency>
        <!--TestNG-->
        <groupId>org.testng</groupId>
        <artifactId>testng</artifactId>
        <version>${testng.version}</version>
        <scope>test</scope>
    </dependency>

    <!--addition of dependency of restassurend -->
    <dependency>
    <groupId>io.rest-assured</groupId>
    <artifactId>rest-assured</artifactId>
    <version>${rest.assured.version}</version>
    <scope>test</scope>
</dependency>

</dependencies>

    <build>
        <plugins>
            <!--compilation plugin-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <!-- maven compiler plugin responsible for compiling the source code, for example  turning a .java file into a .class file -->
                <artifactId>maven-compiler-plugin</artifactId>
                <!-- maven compiler plugin version -->
                <version>3.13.0</version>
                
                <configuration>
                    <!-- Java compiler settings for maven: fecthing the release version from the properties ie 17 -->
                    <release>${maven.compiler.release}</release>
                </configuration>
            </plugin>


            <!-- surefire plugin-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${maven.surefire.version}</version>

                    <configuration>
                        <includes>
                        <include>**/TestRunner.java</include>
                        </includes>
                    </configuration>
            </plugin>
            


        </plugins>
    </build>

</project>